name: yolov5-env
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.17
  - pandas
  - cython
  - pip
  - pytorch=1.12.0
  - torchvision
  - cudatoolkit=11.3
  - matplotlib
  - pillow
  - pyyaml>=5.3
  - scipy
  - tensorboard
  - pip:
    - opencv-python
    - tqdm
    - tensorboardX 